name = "tornbctv-betting"
compatibility_date = "2026-09-07"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "tornbctv-betting"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
