import {json,now} from './_helpers.js';
function ok(request,env){return !env.ADMIN_SECRET || request.headers.get('x-admin-secret')===env.ADMIN_SECRET}
async function eventId(env){const e=await env.DB.prepare("SELECT id FROM events WHERE status IN ('SETUP','LIVE','CLOSED') ORDER BY updated_at DESC LIMIT 1").first();return e?.id||null}
export async function onRequestGet({request,env}){if(!ok(request,env))return json({error:'Unauthorized'},401);const eid=await eventId(env);if(!eid)return json({bets:[]});const r=await env.DB.prepare('SELECT code,player_name,player_id,team_id,amount,status,created_at,paid_at,payout,settled_at FROM bets WHERE event_id=? ORDER BY created_at DESC').bind(eid).all();return json({eventId:eid,bets:r.results||[]})}
export async function onRequestPost({request,env}){if(!ok(request,env))return json({error:'Unauthorized'},401);try{const b=await request.json();const action=String(b.action||'');if(action==='confirm'){if(!b.code)return json({error:'Missing bet code.'},400);const r=await env.DB.prepare("UPDATE bets SET status='PAID',paid_at=? WHERE code=? AND status='AWAITING_PAYMENT'").bind(now(),String(b.code)).run();if(!r.meta?.changes)return json({error:'Bet not found or already confirmed.'},400);await env.DB.prepare('INSERT INTO admin_actions(action,bet_code,details,created_at) VALUES(?,?,?,?)').bind('CONFIRM_PAYMENT',String(b.code),'Manually confirmed',now()).run();return json({ok:true})}
if(action==='unconfirm'){const r=await env.DB.prepare("UPDATE bets SET status='AWAITING_PAYMENT',paid_at=NULL WHERE code=? AND status='PAID'").bind(String(b.code)).run();return json({ok:Boolean(r.meta?.changes)})}
if(action==='winner'){const eid=await eventId(env);if(!eid||!b.teamId)return json({error:'Choose a winner.'},400);await env.DB.prepare("UPDATE events SET winner_team_id=?,status='CLOSED',updated_at=? WHERE id=?").bind(String(b.teamId),now(),eid).run();return json({ok:true,eventId:eid,winnerTeamId:String(b.teamId)})}
if(action==='clearWinner'){const eid=await eventId(env);if(eid)await env.DB.prepare("UPDATE events SET winner_team_id=NULL,status='LIVE',updated_at=? WHERE id=?").bind(now(),eid);return json({ok:true})}
if(action==='markSettled'){const r=await env.DB.prepare("UPDATE bets SET status='SETTLED',settled_at=? WHERE code=? AND status='PAID'").bind(now(),String(b.code)).run();return json({ok:Boolean(r.meta?.changes)})}
return json({error:'Unknown admin action.'},400)}catch(e){return json({error:e.message},500)}}